version: '3.8'

services:
  db:
    image: postgres:15
    container_name: easybill_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: easybill
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./export.sql:/docker-entrypoint-initdb.d/export.sql

volumes:
  pgdata: